
CREATE TABLE kullanicilar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kullanici_adi VARCHAR(50) UNIQUE NOT NULL,
  sifre VARCHAR(255) NOT NULL
);

CREATE TABLE loglar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kullanici_adi VARCHAR(50),
  ip_adres VARCHAR(45),
  tarih TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
